export default {
	HOME: '/',
	LOGIN: '/login',
	LOGOUT: '/logout',
	SIGNUP: '/signup',
	PROFILE: '/profile',
	EVENTS: '/events',
	EVENT: '/event:id',
	CREATE_EVENT: '/events/create',
	MEMBERS: '/members',
	MEMBER: '/member:id',
	CALENDAR: '/calendar',
	REPORTS: '/reports',
	PERMISSIONS: '/permissions',
	CREDENTIALS: '/credentials',
	LOCATIONS: '/locations',
	HACKATHONS: '/hackathons',
	PROJECTS: '/projects',
	DEV: '/dev',
	ANVIL_WIFI: '/anvil-wifi'
};
